
# theme from https://github.com/alacritty/alacritty-theme.git
general.import = [
  # "alacritty-theme/themes/alabaster_dark.toml"
  # "alacritty-theme/themes/kitty.toml"
  "alacritty-theme/themes/enfocado_dark.toml"
  # "alacritty-theme/themes/iterm.toml"
  # "alacritty-theme/themes/catppuccin-mocha.toml"
  # "alacritty-theme/themes/kanagawa_dragon.toml"
  # "alacritty-theme/themes/kanagawa_wave.toml"
  # "alacritty-theme/themes/tokyo_night.toml"
  # "alacritty-theme/themes/aura.toml"
  # "alacritty-theme/themes/ayu_dark.toml"
  # "alacritty-theme/themes/blood_moon.toml"
  # "alacritty-theme/themes/campbell.toml"
]
  
[font]
size = 12.0

[font.bold]
family = "mononoki Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[window]
# startup_mode = "Fullscreen"
startup_mode = "Maximized"

[scrolling]
history=50000

